# Build AI Car & Pedestrian Tracking with Python 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

In [2]:
import cv2
img = cv2.imread('highway-5c6e5194c9e77c0001cda269.jpg')
print(img)

# to resize the image 

resized = cv2.resize(img , (int(img.shape[1]/2) , int(img.shape[0]/2)))

cv2.imshow("car",resized)

cv2.waitKey(5000)

cv2.destroyAllWindows()

[[[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [ 14  29  25]
  [ 19  33  31]
  [ 31  45  43]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [ 17  32  28]
  [ 19  33  31]
  [ 30  44  42]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [ 24  39  35]
  [ 19  33  31]
  [ 26  40  38]]

 ...

 [[ 76  72  53]
  [ 76  72  53]
  [ 75  71  52]
  ...
  [ 59  54  39]
  [ 59  54  39]
  [ 58  53  38]]

 [[ 72  68  49]
  [ 72  68  49]
  [ 71  67  48]
  ...
  [ 59  54  39]
  [ 58  53  38]
  [ 57  52  37]]

 [[ 69  65  46]
  [ 69  65  46]
  [ 69  65  46]
  ...
  [ 58  53  38]
  [ 57  52  37]
  [ 56  51  36]]]


# Detecting with cascades 

In [3]:
car_cascade = cv2.CascadeClassifier('cars.xml')
img = cv2.imread('highway-5c6e5194c9e77c0001cda269.jpg')
gray = cv2.cvtColor(img , cv2.COLOR_BGR2GRAY) # to convert the image to white to black

# detect the cars 
cars = car_cascade.detectMultiScale(gray , 1.1 , 1)

# Draw the Border
for(x,y,w,h) in cars:
    cv2.rectangle(img,(x,y) , (x+w , y+h) , (0,0,255) , 2)

# resizing the image
resized = cv2.resize(img , (int(img.shape[1]/2) , int(img.shape[0]/2)))

cv2.imshow("car",resized)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [16]:
car_cascade = cv2.CascadeClassifier('cars.xml')
img = cv2.imread('car2.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cars = car_cascade.detectMultiScale(gray, 1.1, 1)

for (x, y, w, h) in cars:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2) 

cv2.imshow("car" , img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

# Detecting the Video!!

In [14]:
classifier_file = 'cars.xml'
car_tracker =cv2.CascadeClassifier(classifier_file) 
import cv2,time
video = cv2.VideoCapture('project_video.mp4')

while True:
    (read_succesfull,frame) = video.read()  # to read the current frame
    if read_succesfull:
        grayscaled_frame = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    else:
        break
    
cars = car_tracker.detectMultiScale(grayscaled_frame)

for(x,y,w,h) in cars:
    cv2.rectangle(frame , (x,y) , (x+w , y+h) ,(0,0,255) ,2)
        
    
resize = cv2.resize(frame, (640, 480))
cv2.imshow('car detector' , resize )
cv2.waitKey(1)
cv2.destroyAllWindows()

# it doesnt works
    

error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


In [32]:
import cv2,time
video = cv2.VideoCapture('Tesla Autopilot Dashcam Compilation 2018 Version 360 x 640.mp4')

a = 1
while True:
    a = a+1
    check,frame = video.read()
    print(frame)
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    
    resize = cv2.resize(frame, (640, 480)) 
    cv2.imshow("car", resize) 
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows()

[[[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ...
  [ 77  60  68]
  [ 80  63  71]
  [ 81  64  72]]

 [[184 170 182]
  [161 147 159]
  [136 122 134]
  ...
  [113  96 104]
  [116  99 107]
  [117 100 108]]

 [[182 168 180]
  [160 146 158]
  [133 119 131]
  ...
  [117 100 108]
  [114  97 105]
  [113  96 104]]]
[[[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ..

  [113  96 104]]]
[[[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [254 191 168]
  [254 191 168]
  [254 191 168]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ...
  [ 77  60  68]
  [ 80  63  71]
  [ 81  64  72]]

 [[184 170 182]
  [161 147 159]
  [136 122 134]
  ...
  [113  96 104]
  [116  99 107]
  [117 100 108]]

 [[181 167 179]
  [159 145 157]
  [133 119 131]
  ...
  [117 100 108]
  [114  97 105]
  [113  96 104]]]
[[[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 ...

 [[187 173 185]
  [165 151 163]
  

  [113  96 104]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 197 171]
  [255 198 171]
  [255 198 171]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 199 173]
  [255 200 173]
  [255 198 171]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 200 173]
  [255 200 173]
  [255 198 171]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ...
  [ 77  60  68]
  [ 80  63  71]
  [ 81  64  72]]

 [[184 170 182]
  [161 147 159]
  [136 122 134]
  ...
  [113  96 104]
  [116  99 107]
  [117 100 108]]

 [[181 167 179]
  [159 145 157]
  [133 119 131]
  ...
  [117 100 108]
  [114  97 105]
  [113  96 104]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 198 180]
  [255 199 178]
  [255 199 178]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 199 181]
  [255 199 178]
  [255 199 178]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 199 184]
  [255 199 182]
  [255 198 181]]

 ...

 [[187 173 185]
  [165 151 163]
  

[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [173 144 149]
  [170 141 146]
  [168 139 144]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [170 141 146]
  [173 144 149]
  [171 142 147]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [163 134 139]
  [173 144 149]
  [191 162 167]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ...
  [ 79  60  68]
  [ 82  63  71]
  [ 82  63  71]]

 [[184 170 182]
  [161 147 159]
  [136 122 134]
  ...
  [115  96 104]
  [118  99 107]
  [118  99 107]]

 [[181 167 179]
  [159 145 157]
  [133 119 131]
  ...
  [119 100 108]
  [116  97 105]
  [116  97 105]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [159 130 135]
  [148 119 124]
  [143 114 119]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [163 134 139]
  [153 124 129]
  [147 118 123]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [171 142 147]
  [161 132 137]
  [155 126 131]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ..

  [115  96 104]]]
[[[169 102  84]
  [169 102  84]
  [169 102  84]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 [[169 102  84]
  [169 102  84]
  [169 102  84]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 [[169 102  84]
  [169 102  84]
  [169 102  84]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 ...

 [[189 175 187]
  [162 148 160]
  [133 119 131]
  ...
  [ 76  57  65]
  [ 80  61  69]
  [ 81  62  70]]

 [[187 173 185]
  [159 145 157]
  [131 117 129]
  ...
  [111  92 100]
  [115  96 104]
  [116  97 105]]

 [[183 169 181]
  [157 143 155]
  [130 116 128]
  ...
  [119 100 108]
  [116  97 105]
  [115  96 104]]]
[[[169 102  84]
  [169 102  84]
  [169 102  84]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 [[169 102  84]
  [169 102  84]
  [169 102  84]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 [[169 102  84]
  [169 102  84]
  [169 102  84]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 ...

 [[189 175 187]
  [162 148 160]
  

  [116  97 105]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [141 112 117]
  [141 112 117]
  [141 112 117]]

 ...

 [[203 189 201]
  [165 151 163]
  [130 116 128]
  ...
  [ 79  60  68]
  [ 80  61  69]
  [ 80  61  69]]

 [[200 186 198]
  [162 148 160]
  [129 115 127]
  ...
  [124 105 113]
  [125 106 114]
  [125 106 114]]

 [[198 184 196]
  [160 146 158]
  [127 113 125]
  ...
  [121 102 110]
  [116  97 105]
  [116  97 105]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [142 113 118]
  [142 113 118]
  [142 113 118]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [141 112 117]
  [141 112 117]
  [141 112 117]]

 ...

 [[203 189 201]
  [165 151 163]
  

  [ 92  72  82]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [153 124 129]
  [153 124 129]
  [152 123 128]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [153 124 129]
  [153 124 129]
  [152 123 128]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [150 121 126]
  [150 121 126]
  [150 121 126]]

 ...

 [[208 194 206]
  [167 153 165]
  [127 113 125]
  ...
  [ 62  42  52]
  [ 65  45  55]
  [ 65  45  55]]

 [[204 190 202]
  [164 150 162]
  [126 112 124]
  ...
  [ 89  69  79]
  [ 90  70  80]
  [ 90  70  80]]

 [[201 187 199]
  [161 147 159]
  [126 112 124]
  ...
  [102  82  92]
  [ 97  77  87]
  [ 97  77  87]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [153 124 129]
  [153 124 129]
  [152 123 128]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [153 124 129]
  [153 124 129]
  [152 123 128]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [150 121 126]
  [150 121 126]
  [150 121 126]]

 ...

 [[208 194 206]
  [167 153 165]
  

  [106  88  98]]]
[[[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [245 209 213]
  [241 205 209]
  [238 202 206]]

 [[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [241 205 209]
  [240 204 208]
  [239 203 207]]

 [[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [241 205 209]
  [239 203 207]
  [239 203 207]]

 ...

 [[215 201 213]
  [167 153 165]
  [131 117 129]
  ...
  [ 77  59  69]
  [ 83  65  75]
  [ 85  67  77]]

 [[211 197 209]
  [164 150 162]
  [127 113 125]
  ...
  [129 111 121]
  [131 113 123]
  [131 113 123]]

 [[208 194 206]
  [161 147 159]
  [126 112 124]
  ...
  [117  99 109]
  [109  91 101]
  [106  88  98]]]
[[[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [237 201 205]
  [243 207 211]
  [241 205 209]]

 [[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [198 162 166]
  [239 203 207]
  [240 204 208]]

 [[167 102  84]
  [167 102  84]
  [167 102  84]
  ...
  [180 144 148]
  [246 210 214]
  [247 211 215]]

 ...

 [[215 201 213]
  [167 153 165]
  

  [108  90 100]]]
[[[165 100  82]
  [165 100  82]
  [165 100  82]
  ...
  [154 125 128]
  [145 116 119]
  [140 111 114]]

 [[165 100  82]
  [165 100  82]
  [165 100  82]
  ...
  [154 125 128]
  [145 116 119]
  [140 111 114]]

 [[165 100  82]
  [165 100  82]
  [165 100  82]
  ...
  [154 125 128]
  [146 117 120]
  [140 111 114]]

 ...

 [[215 201 213]
  [167 153 165]
  [131 117 129]
  ...
  [ 79  61  71]
  [ 84  66  76]
  [ 86  68  78]]

 [[211 197 209]
  [165 151 163]
  [129 115 127]
  ...
  [129 111 121]
  [133 115 125]
  [133 115 125]]

 [[210 196 208]
  [162 148 160]
  [127 113 125]
  ...
  [120 102 112]
  [112  94 104]
  [108  90 100]]]
[[[165 100  82]
  [165 100  82]
  [165 100  82]
  ...
  [152 123 126]
  [143 114 117]
  [140 111 114]]

 [[165 100  82]
  [165 100  82]
  [165 100  82]
  ...
  [152 123 126]
  [143 114 117]
  [140 111 114]]

 [[165 100  82]
  [165 100  82]
  [165 100  82]
  ...
  [152 123 126]
  [145 116 119]
  [140 111 114]]

 ...

 [[215 201 213]
  [167 153 165]
  

  [101  83  93]]]
[[[161  99  80]
  [161  99  80]
  [161  99  80]
  ...
  [145 111 117]
  [142 108 114]
  [140 106 112]]

 [[161  99  80]
  [161  99  80]
  [161  99  80]
  ...
  [145 111 117]
  [142 108 114]
  [140 106 112]]

 [[161  99  80]
  [161  99  80]
  [161  99  80]
  ...
  [145 111 117]
  [142 108 114]
  [140 106 112]]

 ...

 [[215 201 213]
  [169 155 167]
  [129 115 127]
  ...
  [ 76  58  68]
  [ 81  63  73]
  [ 84  66  76]]

 [[215 201 213]
  [169 155 167]
  [129 115 127]
  ...
  [122 104 114]
  [126 108 118]
  [126 108 118]]

 [[210 196 208]
  [165 151 163]
  [124 110 122]
  ...
  [114  96 106]
  [106  88  98]
  [101  83  93]]]
[[[161  99  80]
  [161  99  80]
  [161  99  80]
  ...
  [145 111 117]
  [142 108 114]
  [140 106 112]]

 [[161  99  80]
  [161  99  80]
  [161  99  80]
  ...
  [145 111 117]
  [142 108 114]
  [140 106 112]]

 [[161  99  80]
  [161  99  80]
  [161  99  80]
  ...
  [145 111 117]
  [142 108 114]
  [140 106 112]]

 ...

 [[215 201 213]
  [169 155 167]
  

  [101  83  93]]]
[[[158  96  77]
  [160  98  79]
  [161  99  80]
  ...
  [141 109 115]
  [138 106 112]
  [138 106 112]]

 [[158  96  77]
  [160  98  79]
  [161  99  80]
  ...
  [141 109 115]
  [138 106 112]
  [138 106 112]]

 [[158  96  77]
  [160  98  79]
  [161  99  80]
  ...
  [140 108 114]
  [137 105 111]
  [137 105 111]]

 ...

 [[215 201 213]
  [169 155 167]
  [129 115 127]
  ...
  [ 79  61  71]
  [ 84  66  76]
  [ 84  66  76]]

 [[215 201 213]
  [169 155 167]
  [129 115 127]
  ...
  [123 105 115]
  [126 108 118]
  [126 108 118]]

 [[210 196 208]
  [165 151 163]
  [124 110 122]
  ...
  [109  91 101]
  [102  84  94]
  [101  83  93]]]
[[[158  96  77]
  [160  98  79]
  [161  99  80]
  ...
  [138 106 112]
  [136 104 110]
  [136 104 110]]

 [[158  96  77]
  [160  98  79]
  [161  99  80]
  ...
  [138 106 112]
  [136 104 110]
  [136 104 110]]

 [[158  96  77]
  [160  98  79]
  [161  99  80]
  ...
  [140 108 114]
  [137 105 111]
  [136 104 110]]

 ...

 [[215 201 213]
  [169 155 167]
  

  [ 32  13  21]]]
[[[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [138 109 114]
  [136 107 112]
  [136 107 112]]

 [[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [138 109 114]
  [136 107 112]
  [136 107 112]]

 [[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [136 107 112]
  [135 106 111]
  [135 106 111]]

 ...

 [[211 202 213]
  [165 156 167]
  [125 116 127]
  ...
  [ 32  13  21]
  [ 32  13  21]
  [ 32  13  21]]

 [[211 202 213]
  [165 156 167]
  [125 116 127]
  ...
  [ 32  13  21]
  [ 32  13  21]
  [ 32  13  21]]

 [[206 197 208]
  [161 152 163]
  [120 111 122]
  ...
  [ 32  13  21]
  [ 32  13  21]
  [ 32  13  21]]]
[[[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [136 107 112]
  [134 105 110]
  [133 104 109]]

 [[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [136 107 112]
  [134 105 110]
  [133 104 109]]

 [[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [136 107 112]
  [135 106 111]
  [134 105 110]]

 ...

 [[211 202 213]
  [165 156 167]
  

  [112  94 104]]]
[[[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [254 201 176]
  [254 201 176]
  [255 202 177]]

 [[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [254 201 176]
  [254 201 176]
  [255 202 177]]

 [[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [254 201 176]
  [255 202 177]
  [255 202 177]]

 ...

 [[207 198 209]
  [162 153 164]
  [121 112 123]
  ...
  [ 79  61  71]
  [ 78  60  70]
  [ 78  60  70]]

 [[207 198 209]
  [162 153 164]
  [121 112 123]
  ...
  [115  97 107]
  [115  97 107]
  [116  98 108]]

 [[203 194 205]
  [157 148 159]
  [116 107 118]
  ...
  [114  96 106]
  [113  95 105]
  [112  94 104]]]
[[[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [248 194 171]
  [248 194 171]
  [248 194 171]]

 [[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [248 194 171]
  [248 194 171]
  [248 194 171]]

 [[158  96  77]
  [158  96  77]
  [160  98  79]
  ...
  [248 194 171]
  [248 194 171]
  [248 194 171]]

 ...

 [[207 198 209]
  [162 153 164]
  

  [112  94 104]]]
[[[158  95  78]
  [158  95  78]
  [158  95  78]
  ...
  [245 189 166]
  [245 189 166]
  [245 189 166]]

 [[158  95  78]
  [158  95  78]
  [158  95  78]
  ...
  [245 189 166]
  [245 189 166]
  [245 189 166]]

 [[158  95  78]
  [158  95  78]
  [158  95  78]
  ...
  [245 189 166]
  [245 189 166]
  [245 189 166]]

 ...

 [[207 198 209]
  [162 153 164]
  [121 112 123]
  ...
  [ 78  60  70]
  [ 79  61  71]
  [ 78  60  70]]

 [[205 196 207]
  [161 152 163]
  [120 111 122]
  ...
  [115  97 107]
  [115  97 107]
  [116  98 108]]

 [[201 192 203]
  [156 147 158]
  [119 110 121]
  ...
  [115  97 107]
  [114  96 106]
  [112  94 104]]]
[[[154  92  78]
  [154  92  78]
  [154  92  78]
  ...
  [244 188 165]
  [244 188 165]
  [244 188 165]]

 [[154  92  78]
  [154  92  78]
  [154  92  78]
  ...
  [244 188 165]
  [244 188 165]
  [244 188 165]]

 [[154  92  78]
  [154  92  78]
  [154  92  78]
  ...
  [244 188 165]
  [244 188 165]
  [244 188 165]]

 ...

 [[201 192 203]
  [156 147 158]
  

  [110  92 102]]]
[[[154  93  76]
  [154  93  76]
  [156  96  77]
  ...
  [244 188 165]
  [244 188 165]
  [244 188 165]]

 [[154  93  76]
  [154  93  76]
  [156  96  77]
  ...
  [244 188 165]
  [244 188 165]
  [244 188 165]]

 [[155  94  77]
  [154  93  76]
  [156  96  77]
  ...
  [244 189 164]
  [244 189 164]
  [244 189 164]]

 ...

 [[201 192 203]
  [156 147 158]
  [121 112 123]
  ...
  [ 73  55  65]
  [ 73  55  65]
  [ 73  55  65]]

 [[200 191 202]
  [155 146 157]
  [121 112 123]
  ...
  [115  97 107]
  [115  97 107]
  [115  97 107]]

 [[200 191 202]
  [155 146 157]
  [121 112 123]
  ...
  [114  96 106]
  [112  94 104]
  [110  92 102]]]
[[[160 100  81]
  [161 101  82]
  [163 101  82]
  ...
  [250 195 170]
  [250 195 170]
  [250 195 170]]

 [[160 100  81]
  [161 101  82]
  [163 101  82]
  ...
  [250 195 170]
  [250 195 170]
  [250 195 170]]

 [[160 100  81]
  [161 101  82]
  [163 101  82]
  ...
  [249 194 169]
  [249 194 169]
  [249 194 169]]

 ...

 [[201 192 203]
  [156 147 158]
  

  [119 103 108]]]
[[[164 102  83]
  [164 102  83]
  [164 102  83]
  ...
  [249 194 169]
  [249 194 169]
  [249 194 169]]

 [[164 102  83]
  [164 102  83]
  [164 102  83]
  ...
  [249 194 169]
  [249 194 169]
  [249 194 169]]

 [[164 102  83]
  [164 102  83]
  [164 102  83]
  ...
  [249 194 169]
  [249 194 169]
  [249 194 169]]

 ...

 [[220 201 209]
  [180 161 169]
  [139 120 128]
  ...
  [ 76  60  65]
  [ 78  62  67]
  [ 78  62  67]]

 [[218 199 207]
  [178 159 167]
  [140 121 129]
  ...
  [123 107 112]
  [126 110 115]
  [126 110 115]]

 [[218 199 207]
  [177 158 166]
  [142 123 131]
  ...
  [121 105 110]
  [119 103 108]
  [119 103 108]]]
[[[164 102  83]
  [164 102  83]
  [164 102  83]
  ...
  [249 194 169]
  [249 194 169]
  [249 194 169]]

 [[164 102  83]
  [164 102  83]
  [164 102  83]
  ...
  [249 194 169]
  [249 194 169]
  [249 194 169]]

 [[164 102  83]
  [164 102  83]
  [164 102  83]
  ...
  [249 194 169]
  [249 194 169]
  [249 194 169]]

 ...

 [[220 201 209]
  [180 161 169]
  

  [119 103 108]]]
[[[163 101  82]
  [162 100  81]
  [162 100  81]
  ...
  [250 192 168]
  [250 192 168]
  [250 192 168]]

 [[163 101  82]
  [162 100  81]
  [162 100  81]
  ...
  [250 192 168]
  [250 192 168]
  [250 192 168]]

 [[164 102  83]
  [163 101  82]
  [163 101  82]
  ...
  [250 192 168]
  [250 192 168]
  [250 192 168]]

 ...

 [[222 203 211]
  [177 158 166]
  [137 118 126]
  ...
  [ 76  60  65]
  [ 78  62  67]
  [ 78  62  67]]

 [[221 202 210]
  [175 156 164]
  [138 119 127]
  ...
  [123 107 112]
  [126 110 115]
  [126 110 115]]

 [[221 202 210]
  [174 155 163]
  [140 121 129]
  ...
  [121 105 110]
  [119 103 108]
  [119 103 108]]]
[[[163 101  82]
  [162 100  81]
  [162 100  81]
  ...
  [250 192 168]
  [250 192 168]
  [250 192 168]]

 [[163 101  82]
  [162 100  81]
  [162 100  81]
  ...
  [250 192 168]
  [250 192 168]
  [250 192 168]]

 [[164 102  83]
  [163 101  82]
  [163 101  82]
  ...
  [250 192 168]
  [250 192 168]
  [250 192 168]]

 ...

 [[222 203 211]
  [177 158 166]
  

[[[104  96 111]
  [105  97 112]
  [107  97 112]
  ...
  [248 189 167]
  [248 189 167]
  [248 189 167]]

 [[104  96 111]
  [104  96 111]
  [108  98 113]
  ...
  [248 189 167]
  [248 189 167]
  [248 189 167]]

 [[109 101 116]
  [105  97 112]
  [104  96 111]
  ...
  [248 189 167]
  [248 189 167]
  [248 189 167]]

 ...

 [[219 201 211]
  [173 155 165]
  [137 119 129]
  ...
  [ 73  57  62]
  [ 77  61  66]
  [ 79  63  68]]

 [[218 200 210]
  [172 154 164]
  [137 119 129]
  ...
  [124 108 113]
  [128 112 117]
  [129 113 118]]

 [[218 200 210]
  [171 153 163]
  [137 119 129]
  ...
  [121 105 110]
  [117 101 106]
  [115  99 104]]]
285


In [ ]:
cars = car_cascade.detectMultiScale(gray , 1.1 , 1)

# Draw the Border
for(x,y,w,h) in cars:
    cv2.rectangle(frame,(x,y) , (x+w , y+h) , (0,0,255) , 2)

In [33]:
import cv2,time
car_cascade = cv2.CascadeClassifier('cars.xml')
video = cv2.VideoCapture('Tesla Autopilot Dashcam Compilation 2018 Version 360 x 640.mp4')

a = 1
while True:
    a = a+1
    check,frame = video.read()
    print(frame)
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    cars = car_cascade.detectMultiScale(gray , 1.1 , 1)
    
    for (x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y) , (x+w , y+h) , (255,0,0) , 2)
    
    resize = cv2.resize(frame, (640, 480)) 
    cv2.imshow("car", resize) 
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows()

[[[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ...
  [ 77  60  68]
  [ 80  63  71]
  [ 81  64  72]]

 [[184 170 182]
  [161 147 159]
  [136 122 134]
  ...
  [113  96 104]
  [116  99 107]
  [117 100 108]]

 [[182 168 180]
  [160 146 158]
  [133 119 131]
  ...
  [117 100 108]
  [114  97 105]
  [113  96 104]]]
[[[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 102  79]
  [167 102  79]
  [167 102  79]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ..

[[[167 104  87]
  [167 104  87]
  [167 104  87]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 104  87]
  [167 104  87]
  [167 104  87]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[167 104  87]
  [167 104  87]
  [167 104  87]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ...
  [ 77  60  68]
  [ 80  63  71]
  [ 81  64  72]]

 [[184 170 182]
  [161 147 159]
  [136 122 134]
  ...
  [113  96 104]
  [116  99 107]
  [117 100 108]]

 [[181 167 179]
  [159 145 157]
  [133 119 131]
  ...
  [117 100 108]
  [114  97 105]
  [113  96 104]]]
[[[169 104  86]
  [169 104  86]
  [169 104  86]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[169 104  86]
  [169 104  86]
  [169 104  86]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 [[169 104  86]
  [169 104  86]
  [169 104  86]
  ...
  [252 192 168]
  [252 192 168]
  [252 192 168]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ..

  [113  96 104]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [253 193 169]
  [253 193 169]
  [253 193 169]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [253 193 169]
  [253 193 169]
  [253 193 169]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 192 169]
  [255 192 169]
  [255 192 169]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ...
  [ 77  60  68]
  [ 80  63  71]
  [ 81  64  72]]

 [[184 170 182]
  [161 147 159]
  [136 122 134]
  ...
  [113  96 104]
  [116  99 107]
  [117 100 108]]

 [[181 167 179]
  [159 145 157]
  [133 119 131]
  ...
  [117 100 108]
  [114  97 105]
  [113  96 104]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 192 169]
  [255 192 169]
  [255 192 169]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 192 169]
  [255 192 169]
  [255 192 169]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [255 192 169]
  [254 191 168]
  [254 191 168]]

 ...

 [[187 173 185]
  [165 151 163]
  

[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [154 122 128]
  [154 122 128]
  [154 122 128]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [154 122 128]
  [154 122 128]
  [154 122 128]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [154 122 128]
  [154 122 128]
  [154 122 128]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ...
  [ 75  56  64]
  [ 80  61  69]
  [ 82  63  71]]

 [[184 170 182]
  [161 147 159]
  [136 122 134]
  ...
  [111  92 100]
  [116  97 105]
  [118  99 107]]

 [[181 167 179]
  [159 145 157]
  [133 119 131]
  ...
  [124 105 113]
  [118  99 107]
  [116  97 105]]]
[[[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [158 126 132]
  [156 124 130]
  [155 123 129]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [161 129 135]
  [158 126 132]
  [157 125 131]]

 [[169 103  82]
  [169 103  82]
  [169 103  82]
  ...
  [165 133 139]
  [157 125 131]
  [156 124 130]]

 ...

 [[187 173 185]
  [165 151 163]
  [138 124 136]
  ..

# Detecting the Pedestrains 

In [36]:
import cv2,time
pedestrian_detector = cv2.CascadeClassifier('pedestrian.xml')
video = cv2.VideoCapture('Pedestrians Compilation 480 x 854.mp4')

a = 1
while True:
    a = a+1
    check,frame = video.read()
    print(frame)
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    pedestrians = pedestrian_detector.detectMultiScale(gray , 3.5 , 1)
    cars = car_cascade.detectMultiScale(gray , 1.1 , 1)
        
    for (x,y,w,h) in pedestrians:
        cv2.rectangle(frame,(x,y) , (x+w , y+h) , (255,0,0) , 2)
    
    for (x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y) , (x+w , y+h) , (0,0,255) , 2)
    resize = cv2.resize(frame, (640, 480)) 
    cv2.imshow("car", resize) 
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows()

[[[ 69  69  69]
  [ 73  73  73]
  [ 75  75  75]
  ...
  [ 69  69  69]
  [ 69  69  69]
  [ 68  68  68]]

 [[ 73  73  73]
  [ 78  78  78]
  [ 78  78  78]
  ...
  [ 69  69  69]
  [ 69  69  69]
  [ 68  68  68]]

 [[ 75  75  75]
  [ 78  78  78]
  [ 81  81  81]
  ...
  [ 69  69  69]
  [ 69  69  69]
  [ 68  68  68]]

 ...

 [[176 157 156]
  [187 168 167]
  [190 171 170]
  ...
  [210 198 198]
  [209 197 197]
  [205 193 193]]

 [[173 154 153]
  [183 164 163]
  [187 168 167]
  ...
  [209 197 197]
  [207 195 195]
  [202 190 190]]

 [[162 143 142]
  [173 154 153]
  [176 157 156]
  ...
  [198 186 186]
  [197 185 185]
  [192 180 180]]]
[[[ 71  71  71]
  [ 75  75  75]
  [ 75  75  75]
  ...
  [ 69  69  69]
  [ 69  69  69]
  [ 68  68  68]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 79  79  79]
  ...
  [ 69  69  69]
  [ 69  69  69]
  [ 68  68  68]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 80  80  80]
  ...
  [ 69  69  69]
  [ 69  69  69]
  [ 68  68  68]]

 ...

 [[176 157 156]
  [187 168 167]
  [190 171 170]
  ..

[[[ 71  71  71]
  [ 75  75  75]
  [ 75  75  75]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 79  79  79]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 80  80  80]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 ...

 [[176 157 156]
  [187 168 167]
  [190 171 170]
  ...
  [208 199 196]
  [207 198 195]
  [203 194 191]]

 [[173 154 153]
  [183 164 163]
  [187 168 167]
  ...
  [207 198 195]
  [205 196 193]
  [200 191 188]]

 [[162 143 142]
  [173 154 153]
  [176 157 156]
  ...
  [196 187 184]
  [195 186 183]
  [190 181 178]]]
[[[ 71  71  71]
  [ 75  75  75]
  [ 75  75  75]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 79  79  79]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 80  80  80]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 ...

 [[176 157 156]
  [187 168 167]
  [190 171 170]
  ..

[[[ 71  71  71]
  [ 75  75  75]
  [ 75  75  75]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 79  79  79]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 80  80  80]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 ...

 [[176 157 156]
  [187 168 167]
  [190 171 170]
  ...
  [208 199 196]
  [207 198 195]
  [203 194 191]]

 [[173 154 153]
  [183 164 163]
  [187 168 167]
  ...
  [207 198 195]
  [205 196 193]
  [200 191 188]]

 [[162 143 142]
  [173 154 153]
  [176 157 156]
  ...
  [196 187 184]
  [195 186 183]
  [190 181 178]]]
[[[ 71  71  71]
  [ 75  75  75]
  [ 75  75  75]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 79  79  79]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 [[ 75  75  75]
  [ 79  79  79]
  [ 80  80  80]
  ...
  [ 69  68  70]
  [ 69  68  70]
  [ 68  67  69]]

 ...

 [[176 157 156]
  [187 168 167]
  [190 171 170]
  ..

[[[ 65  65  65]
  [ 69  69  69]
  [ 69  69  69]
  ...
  [ 62  61  63]
  [ 61  60  62]
  [ 61  60  62]]

 [[ 69  69  69]
  [ 73  73  73]
  [ 73  73  73]
  ...
  [ 62  61  63]
  [ 61  60  62]
  [ 61  60  62]]

 [[ 69  69  69]
  [ 73  73  73]
  [ 74  74  74]
  ...
  [ 62  61  63]
  [ 61  60  62]
  [ 61  60  62]]

 ...

 [[169 150 149]
  [180 161 160]
  [183 164 163]
  ...
  [201 192 189]
  [198 189 186]
  [195 186 183]]

 [[166 147 146]
  [176 157 156]
  [180 161 160]
  ...
  [201 192 189]
  [197 188 185]
  [194 185 182]]

 [[155 136 135]
  [166 147 146]
  [169 150 149]
  ...
  [191 182 179]
  [189 180 177]
  [186 177 174]]]
[[[ 66  66  66]
  [ 71  71  71]
  [ 69  69  69]
  ...
  [ 60  59  61]
  [ 60  59  61]
  [ 60  59  61]]

 [[ 66  66  66]
  [ 71  71  71]
  [ 69  69  69]
  ...
  [ 60  59  61]
  [ 60  59  61]
  [ 60  59  61]]

 [[ 66  66  66]
  [ 71  71  71]
  [ 69  69  69]
  ...
  [ 60  59  61]
  [ 60  59  61]
  [ 60  59  61]]

 ...

 [[167 148 147]
  [177 158 157]
  [181 162 161]
  ..

[[[ 59  59  59]
  [ 62  62  62]
  [ 61  61  61]
  ...
  [ 52  51  53]
  [ 52  51  53]
  [ 52  51  53]]

 [[ 59  59  59]
  [ 62  62  62]
  [ 61  61  61]
  ...
  [ 53  52  54]
  [ 53  52  54]
  [ 52  51  53]]

 [[ 59  59  59]
  [ 62  62  62]
  [ 61  61  61]
  ...
  [ 53  52  54]
  [ 53  52  54]
  [ 52  51  53]]

 ...

 [[160 142 139]
  [170 152 149]
  [172 154 151]
  ...
  [188 180 175]
  [186 178 173]
  [182 174 169]]

 [[156 138 135]
  [167 149 146]
  [168 150 147]
  ...
  [187 179 174]
  [184 176 171]
  [181 173 168]]

 [[149 131 128]
  [159 141 138]
  [160 142 139]
  ...
  [180 172 167]
  [178 170 165]
  [174 166 161]]]
[[[ 58  58  58]
  [ 61  61  61]
  [ 60  60  60]
  ...
  [ 51  50  52]
  [ 51  50  52]
  [ 50  49  51]]

 [[ 58  58  58]
  [ 61  61  61]
  [ 60  60  60]
  ...
  [ 52  51  53]
  [ 52  51  53]
  [ 51  50  52]]

 [[ 58  58  58]
  [ 61  61  61]
  [ 60  60  60]
  ...
  [ 52  51  53]
  [ 52  51  53]
  [ 51  50  52]]

 ...

 [[159 141 138]
  [169 151 148]
  [170 152 149]
  ..

[[[ 52  52  52]
  [ 54  54  54]
  [ 53  53  53]
  ...
  [ 46  45  47]
  [ 46  45  47]
  [ 45  44  46]]

 [[ 52  52  52]
  [ 54  54  54]
  [ 53  53  53]
  ...
  [ 46  45  47]
  [ 46  45  47]
  [ 45  44  46]]

 [[ 52  52  52]
  [ 54  54  54]
  [ 53  53  53]
  ...
  [ 46  45  47]
  [ 46  45  47]
  [ 45  44  46]]

 ...

 [[144 130 128]
  [155 141 139]
  [156 142 140]
  ...
  [179 169 169]
  [178 168 168]
  [174 164 164]]

 [[143 129 127]
  [154 140 138]
  [155 141 139]
  ...
  [176 166 166]
  [174 164 164]
  [172 162 162]]

 [[137 123 121]
  [148 134 132]
  [149 135 133]
  ...
  [172 162 162]
  [171 161 161]
  [167 157 157]]]
[[[ 52  52  52]
  [ 54  54  54]
  [ 53  53  53]
  ...
  [ 45  45  45]
  [ 45  45  45]
  [ 45  45  45]]

 [[ 52  52  52]
  [ 54  54  54]
  [ 53  53  53]
  ...
  [ 45  45  45]
  [ 45  45  45]
  [ 45  45  45]]

 [[ 52  52  52]
  [ 54  54  54]
  [ 53  53  53]
  ...
  [ 45  45  45]
  [ 45  45  45]
  [ 44  44  44]]

 ...

 [[145 131 129]
  [156 142 140]
  [157 143 141]
  ..

[[[ 46  46  46]
  [ 46  46  46]
  [ 46  46  46]
  ...
  [ 39  39  39]
  [ 39  39  39]
  [ 39  39  39]]

 [[ 46  46  46]
  [ 46  46  46]
  [ 46  46  46]
  ...
  [ 39  39  39]
  [ 39  39  39]
  [ 39  39  39]]

 [[ 46  46  46]
  [ 46  46  46]
  [ 46  46  46]
  ...
  [ 39  39  39]
  [ 39  39  39]
  [ 39  39  39]]

 ...

 [[137 123 121]
  [148 134 132]
  [149 135 133]
  ...
  [169 162 159]
  [167 160 157]
  [164 157 154]]

 [[136 122 120]
  [147 133 131]
  [148 134 132]
  ...
  [167 160 157]
  [165 158 155]
  [163 156 153]]

 [[130 116 114]
  [141 127 125]
  [142 128 126]
  ...
  [163 156 153]
  [162 155 152]
  [158 151 148]]]
[[[ 45  45  45]
  [ 45  45  45]
  [ 45  45  45]
  ...
  [ 38  38  38]
  [ 38  38  38]
  [ 38  38  38]]

 [[ 45  45  45]
  [ 45  45  45]
  [ 45  45  45]
  ...
  [ 38  38  38]
  [ 38  38  38]
  [ 38  38  38]]

 [[ 45  45  45]
  [ 45  45  45]
  [ 45  45  45]
  ...
  [ 38  38  38]
  [ 38  38  38]
  [ 38  38  38]]

 ...

 [[136 122 120]
  [147 133 131]
  [148 134 132]
  ..

[[[ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 30  30  30]]

 [[ 38  38  38]
  [ 38  38  38]
  [ 38  38  38]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 30  30  30]]

 [[ 38  38  38]
  [ 38  38  38]
  [ 38  38  38]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 30  30  30]]

 ...

 [[124 117 114]
  [135 128 125]
  [137 130 127]
  ...
  [156 153 147]
  [155 152 146]
  [151 148 142]]

 [[124 117 114]
  [135 128 125]
  [135 128 125]
  ...
  [155 152 146]
  [153 150 144]
  [150 147 141]]

 [[118 111 108]
  [129 122 119]
  [129 122 119]
  ...
  [150 147 141]
  [149 146 140]
  [146 143 137]]]
[[[ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 30  30  30]]

 [[ 38  38  38]
  [ 38  38  38]
  [ 38  38  38]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 30  30  30]]

 [[ 38  38  38]
  [ 38  38  38]
  [ 38  38  38]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 30  30  30]]

 ...

 [[124 117 114]
  [135 128 125]
  [137 130 127]
  ..

[[[ 32  32  32]
  [ 32  32  32]
  [ 32  32  32]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 [[ 32  32  32]
  [ 32  32  32]
  [ 32  32  32]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 [[ 32  32  32]
  [ 32  32  32]
  [ 32  32  32]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 ...

 [[119 114 113]
  [127 122 121]
  [125 120 119]
  ...
  [147 142 141]
  [147 142 141]
  [143 138 137]]

 [[118 113 112]
  [126 121 120]
  [125 120 119]
  ...
  [148 143 142]
  [146 141 140]
  [143 138 137]]

 [[114 109 108]
  [122 117 116]
  [119 114 113]
  ...
  [143 138 137]
  [142 137 136]
  [139 134 133]]]
[[[ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]
  ...
  [ 23  23  23]
  [ 23  23  23]
  [ 23  23  23]]

 [[ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]
  ...
  [ 23  23  23]
  [ 23  23  23]
  [ 23  23  23]]

 [[ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]
  ...
  [ 23  23  23]
  [ 23  23  23]
  [ 23  23  23]]

 ...

 [[118 113 112]
  [126 121 120]
  [123 118 117]
  ..

[[[ 25  25  25]
  [ 25  25  25]
  [ 25  25  25]
  ...
  [ 18  18  18]
  [ 18  18  18]
  [ 17  17  17]]

 [[ 25  25  25]
  [ 25  25  25]
  [ 25  25  25]
  ...
  [ 18  18  18]
  [ 18  18  18]
  [ 17  17  17]]

 [[ 25  25  25]
  [ 25  25  25]
  [ 25  25  25]
  ...
  [ 18  18  18]
  [ 18  18  18]
  [ 17  17  17]]

 ...

 [[112 108 104]
  [120 116 112]
  [118 114 110]
  ...
  [137 133 129]
  [137 133 129]
  [134 130 126]]

 [[111 107 103]
  [119 115 111]
  [116 112 108]
  ...
  [139 135 131]
  [137 133 129]
  [135 131 127]]

 [[107 103  99]
  [115 111 107]
  [113 109 105]
  ...
  [135 131 127]
  [134 130 126]
  [130 126 122]]]
[[[ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 16  16  16]]

 [[ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 16  16  16]]

 [[ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 16  16  16]]

 ...

 [[112 108 104]
  [120 116 112]
  [118 114 110]
  ..

[[[ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]
  ...
  [ 13  13  13]
  [ 13  13  13]
  [ 12  12  12]]

 [[ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]
  ...
  [ 13  13  13]
  [ 13  13  13]
  [ 12  12  12]]

 [[ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]
  ...
  [ 13  13  13]
  [ 13  13  13]
  [ 12  12  12]]

 ...

 [[105 102 101]
  [110 107 106]
  [111 108 107]
  ...
  [123 123 121]
  [123 123 121]
  [119 119 117]]

 [[105 102 101]
  [110 107 106]
  [110 107 106]
  ...
  [124 124 122]
  [123 123 121]
  [121 121 119]]

 [[103 100  99]
  [106 103 102]
  [106 103 102]
  ...
  [121 121 119]
  [119 119 117]
  [116 116 114]]]
[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[105 102 101]
  [110 107 106]
  [111 108 107]
  ..

[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ...
  [126 126 126]
  [123 123 123]
  [119 119 119]]

 [[101 101 101]
  [103 103 103]
  [105 105 105]
  ...
  [124 124 124]
  [128 128 128]
  [121 121 121]]

 [[100 100 100]
  [101 101 101]
  [104 104 104]
  ...
  [123 123 123]
  [128 128 128]
  [123 123 123]]]
[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ..

[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ...
  [126 126 126]
  [123 123 123]
  [119 119 119]]

 [[101 101 101]
  [103 103 103]
  [105 105 105]
  ...
  [124 124 124]
  [128 128 128]
  [121 121 121]]

 [[100 100 100]
  [101 101 101]
  [104 104 104]
  ...
  [123 123 123]
  [128 128 128]
  [123 123 123]]]
[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ..

[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ...
  [126 126 126]
  [123 123 123]
  [119 119 119]]

 [[101 101 101]
  [103 103 103]
  [105 105 105]
  ...
  [124 124 124]
  [128 128 128]
  [121 121 121]]

 [[100 100 100]
  [101 101 101]
  [104 104 104]
  ...
  [123 123 123]
  [128 128 128]
  [123 123 123]]]
[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ..

[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ...
  [126 126 126]
  [123 123 123]
  [119 119 119]]

 [[101 101 101]
  [103 103 103]
  [105 105 105]
  ...
  [124 124 124]
  [128 128 128]
  [121 121 121]]

 [[100 100 100]
  [101 101 101]
  [104 104 104]
  ...
  [123 123 123]
  [128 128 128]
  [123 123 123]]]
[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ..

[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ...
  [126 126 126]
  [123 123 123]
  [119 119 119]]

 [[101 101 101]
  [103 103 103]
  [105 105 105]
  ...
  [124 124 124]
  [128 128 128]
  [121 121 121]]

 [[100 100 100]
  [101 101 101]
  [104 104 104]
  ...
  [123 123 123]
  [128 128 128]
  [123 123 123]]]
[[[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ...
  [ 12  12  12]
  [ 12  12  12]
  [ 11  11  11]]

 ...

 [[104 104 104]
  [105 105 105]
  [109 109 109]
  ..

[[[ 15  15  15]
  [ 15  15  15]
  [ 15  15  15]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 [[ 15  15  15]
  [ 15  15  15]
  [ 15  15  15]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 [[ 15  15  15]
  [ 15  15  15]
  [ 15  15  15]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 ...

 [[ 94  94  94]
  [ 95  95  95]
  [ 98  98  98]
  ...
  [114 114 114]
  [111 111 111]
  [108 108 108]]

 [[ 90  90  90]
  [ 93  93  93]
  [ 95  95  95]
  ...
  [112 112 112]
  [115 115 115]
  [109 109 109]]

 [[ 89  89  89]
  [ 90  90  90]
  [ 94  94  94]
  ...
  [111 111 111]
  [115 115 115]
  [111 111 111]]]
[[[ 15  15  15]
  [ 15  15  15]
  [ 15  15  15]
  ...
  [  9   9   9]
  [  9   9   9]
  [  9   9   9]]

 [[ 15  15  15]
  [ 15  15  15]
  [ 15  15  15]
  ...
  [  9   9   9]
  [  9   9   9]
  [  9   9   9]]

 [[ 15  15  15]
  [ 15  15  15]
  [ 15  15  15]
  ...
  [  9   9   9]
  [  9   9   9]
  [  9   9   9]]

 ...

 [[ 91  91  91]
  [ 93  93  93]
  [ 96  96  96]
  ..

[[[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[50 50 50]
  [51 51 51]
  [54 54 54]
  ...
  [64 64 64]
  [61 61 61]
  [58 58 58]]

 [[47 47 47]
  [48 48 48]
  [51 51 51]
  ...
  [62 62 62]
  [64 64 64]
  [59 59 59]]

 [[47 47 47]
  [47 47 47]
  [50 50 50]
  ...
  [61 61 61]
  [64 64 64]
  [61 61 61]]]
[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[46 46 44]
  [47 47 45]
  [51 51 49]
  ...
  [59 59 57]
  [57 57 55]
  [53 53 51]]

 [[45 45 43]
  [45 45 43]
  [47 47 45]
  ...
  [58 58 56]
  [60 60 58]
  [54 54 52]]

 [[45 45 43]
  [45 45 43]
  [46 46 44]
  .

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[169 173 189]
  [177 181 197]
  [180 184 200]
  ...
  [253 245 235]
  [254 243 234]
  [253 242 233]]

 [[170 174 190]
  [178 182 198]
  [180 184 200]
  ...
  [254 246 236]
  [255 245 236]
  [255 245 236]]

 [[169 175 191]
  [177 183 199]
  [178 184 200]
  ...
  [254 246 236]
  [255 247 237]
  [255 247 237]]

 ...

 [[ 87  87  94]
  [ 87  87  94]
  [ 87  87  94]
  ...
  [ 45  37  37]
  [ 45  37  37]
  [ 45  37  37]]

 [[ 87  87  94]
  [ 87  87  94]
  [ 87  87  94]
  ...
  [ 45  37  37]
  [ 45  37  37]
  [ 45  37  37]]

 [[ 87  87  94]
  [ 87  87  94]
  [ 87  87  94]
  ...
  [ 45  37  37]
  [ 45  37  37]
  [ 45  37  37]]]
[[[176 176 176]
  [176 176 176]
  [176 176 176]
  ...
  [253 245 235]
  [254 243 234]
  [253 242 233]]

 [[176 176 176]
  [176 176 176]
  [176 176 176]
  ...
  [254 246 236]
  [255 245 236]
  [255 245 236]]

 [[176 176 176]
  [176 176 176]
  [176 176 176]
  ...
  [254 246 236]
  [255 247 237]
  [255 247 237]]

 ...

 [[ 87  87  94]
  [ 87  87  94]
  [ 87  87  94]
  ..

[[[ 55  63  72]
  [ 44  52  61]
  [ 46  54  63]
  ...
  [239 209 196]
  [238 208 195]
  [238 208 195]]

 [[ 93 101 110]
  [ 80  88  97]
  [ 75  83  92]
  ...
  [241 211 198]
  [240 210 197]
  [240 210 197]]

 [[119 127 136]
  [111 119 128]
  [106 114 123]
  ...
  [241 215 202]
  [240 214 201]
  [239 213 200]]

 ...

 [[ 54  56  63]
  [ 55  57  64]
  [ 54  56  63]
  ...
  [ 44  36  36]
  [ 44  36  36]
  [ 44  36  36]]

 [[ 50  52  59]
  [ 52  54  61]
  [ 52  54  61]
  ...
  [ 44  36  36]
  [ 44  36  36]
  [ 44  36  36]]

 [[ 49  51  58]
  [ 50  52  59]
  [ 50  52  59]
  ...
  [ 44  36  36]
  [ 44  36  36]
  [ 44  36  36]]]
[[[149 157 166]
  [153 161 170]
  [156 164 173]
  ...
  [241 213 200]
  [239 211 198]
  [239 211 198]]

 [[ 36  44  53]
  [ 37  45  54]
  [ 40  48  57]
  ...
  [245 217 204]
  [244 216 203]
  [243 215 202]]

 [[ 94 102 111]
  [ 89  97 106]
  [ 86  94 103]
  ...
  [244 222 205]
  [245 223 206]
  [245 223 206]]

 ...

 [[ 54  56  63]
  [ 55  57  64]
  [ 54  56  63]
  ..

[[[185 190 203]
  [181 186 199]
  [180 185 198]
  ...
  [239 209 187]
  [241 211 189]
  [242 212 190]]

 [[177 182 195]
  [177 182 195]
  [177 182 195]
  ...
  [239 209 187]
  [241 211 189]
  [242 212 190]]

 [[161 166 179]
  [164 169 182]
  [167 172 185]
  ...
  [239 209 187]
  [241 211 189]
  [242 212 190]]

 ...

 [[ 98  99 109]
  [ 99 100 110]
  [103 104 114]
  ...
  [ 52  44  44]
  [ 52  44  44]
  [ 52  44  44]]

 [[ 98  99 109]
  [ 95  96 106]
  [ 98  99 109]
  ...
  [ 52  44  44]
  [ 52  44  44]
  [ 52  44  44]]

 [[ 99 100 110]
  [ 95  96 106]
  [ 98  99 109]
  ...
  [ 52  44  44]
  [ 52  44  44]
  [ 52  44  44]]]
[[[103 108 121]
  [101 106 119]
  [ 99 104 117]
  ...
  [233 213 189]
  [245 225 201]
  [248 228 204]]

 [[127 132 145]
  [128 133 146]
  [129 134 147]
  ...
  [233 213 189]
  [245 225 201]
  [248 228 204]]

 [[176 181 194]
  [180 185 198]
  [188 191 202]
  ...
  [233 213 189]
  [245 225 201]
  [248 228 204]]

 ...

 [[104 105 115]
  [106 107 117]
  [112 114 121]
  ..

[[[194 209 220]
  [186 201 212]
  [163 178 189]
  ...
  [232 209 195]
  [231 208 194]
  [230 207 193]]

 [[196 211 222]
  [182 197 208]
  [183 198 209]
  ...
  [232 209 195]
  [231 208 194]
  [230 207 193]]

 [[195 212 223]
  [177 194 205]
  [191 206 217]
  ...
  [232 209 195]
  [231 208 194]
  [230 207 193]]

 ...

 [[104 107 112]
  [103 106 111]
  [ 99 101 108]
  ...
  [ 50  42  42]
  [ 50  42  42]
  [ 50  42  42]]

 [[103 106 111]
  [102 105 110]
  [ 98 100 107]
  ...
  [ 50  42  42]
  [ 50  42  42]
  [ 50  42  42]]

 [[103 106 111]
  [100 103 108]
  [ 97  99 106]
  ...
  [ 50  42  42]
  [ 50  42  42]
  [ 50  42  42]]]
[[[ 86  98 110]
  [ 36  48  60]
  [ 35  45  55]
  ...
  [231 208 194]
  [231 208 194]
  [231 208 194]]

 [[ 61  73  85]
  [ 35  47  59]
  [ 38  48  58]
  ...
  [231 208 194]
  [231 208 194]
  [231 208 194]]

 [[ 42  54  64]
  [ 36  48  58]
  [ 40  50  60]
  ...
  [231 208 194]
  [231 208 194]
  [231 208 194]]

 ...

 [[104 107 112]
  [103 106 111]
  [ 99 101 108]
  ..

[[[198 208 220]
  [202 212 224]
  [202 212 224]
  ...
  [219 190 174]
  [220 188 173]
  [220 188 173]]

 [[193 203 215]
  [194 204 216]
  [193 203 215]
  ...
  [217 188 172]
  [218 186 171]
  [218 186 171]]

 [[190 200 212]
  [201 211 223]
  [207 217 229]
  ...
  [218 189 173]
  [219 188 171]
  [218 187 170]]

 ...

 [[ 97  99 106]
  [ 92  94 101]
  [ 84  86  93]
  ...
  [ 52  44  46]
  [ 52  44  46]
  [ 52  44  46]]

 [[ 98 100 107]
  [ 92  94 101]
  [ 83  85  92]
  ...
  [ 52  44  46]
  [ 52  44  46]
  [ 52  44  46]]

 [[ 97  99 106]
  [ 91  93 100]
  [ 83  85  92]
  ...
  [ 52  44  46]
  [ 52  44  46]
  [ 52  44  46]]]
[[[200 210 222]
  [200 210 222]
  [202 212 224]
  ...
  [219 190 174]
  [219 188 171]
  [218 187 170]]

 [[193 203 215]
  [196 206 218]
  [201 211 223]
  ...
  [219 190 174]
  [219 188 171]
  [219 188 171]]

 [[207 217 229]
  [205 215 227]
  [203 213 225]
  ...
  [222 191 174]
  [222 189 170]
  [221 188 169]]

 ...

 [[ 86  84  89]
  [ 86  84  89]
  [ 86  84  89]
  ..

[[[154 164 176]
  [137 147 159]
  [126 133 146]
  ...
  [223 185 155]
  [226 183 152]
  [225 182 151]]

 [[144 154 166]
  [138 148 160]
  [141 148 161]
  ...
  [223 185 155]
  [226 183 152]
  [225 182 151]]

 [[129 139 151]
  [137 147 159]
  [154 161 174]
  ...
  [224 186 156]
  [223 183 153]
  [220 180 150]]

 ...

 [[ 95  93  98]
  [ 94  92  97]
  [ 96  91  97]
  ...
  [ 52  45  42]
  [ 52  45  42]
  [ 52  45  42]]

 [[ 94  92  97]
  [ 91  89  94]
  [ 95  90  96]
  ...
  [ 52  45  42]
  [ 52  45  42]
  [ 52  45  42]]

 [[ 91  89  94]
  [ 89  87  92]
  [ 91  86  92]
  ...
  [ 52  45  42]
  [ 52  45  42]
  [ 52  45  42]]]
[[[156 163 176]
  [174 181 194]
  [176 186 198]
  ...
  [220 185 152]
  [222 183 149]
  [220 181 147]]

 [[167 174 187]
  [176 183 196]
  [177 187 199]
  ...
  [220 185 152]
  [222 183 149]
  [219 180 146]]

 [[170 177 190]
  [176 183 196]
  [177 187 199]
  ...
  [223 183 151]
  [221 178 147]
  [218 175 144]]

 ...

 [[ 86  84  89]
  [ 86  84  89]
  [ 88  86  91]
  ..

[[[186 202 209]
  [186 202 209]
  [186 202 209]
  ...
  [128  73  53]
  [119  68  49]
  [122  71  52]]

 [[186 202 209]
  [186 202 209]
  [186 202 209]
  ...
  [123  68  48]
  [119  68  49]
  [121  70  51]]

 [[187 203 210]
  [187 203 210]
  [187 203 210]
  ...
  [123  70  50]
  [120  71  52]
  [120  71  52]]

 ...

 [[ 89  87  92]
  [ 89  87  92]
  [ 86  84  89]
  ...
  [ 51  44  41]
  [ 51  44  41]
  [ 51  44  41]]

 [[ 86  84  89]
  [ 86  84  89]
  [ 82  80  85]
  ...
  [ 51  44  41]
  [ 51  44  41]
  [ 51  44  41]]

 [[ 86  84  89]
  [ 86  84  89]
  [ 82  80  85]
  ...
  [ 51  44  41]
  [ 51  44  41]
  [ 51  44  41]]]
[[[162 178 185]
  [162 178 185]
  [158 174 181]
  ...
  [121  63  52]
  [121  67  58]
  [121  67  58]]

 [[168 184 191]
  [168 184 191]
  [169 185 192]
  ...
  [121  63  52]
  [119  65  56]
  [119  65  56]]

 [[182 198 205]
  [182 198 205]
  [179 195 202]
  ...
  [119  63  52]
  [119  67  58]
  [117  65  56]]

 ...

 [[ 86  84  89]
  [ 87  85  90]
  [ 89  84  90]
  ..

[[[151 166 177]
  [151 166 177]
  [149 164 175]
  ...
  [ 82  59  45]
  [ 80  59  45]
  [ 79  58  44]]

 [[151 166 177]
  [151 166 177]
  [150 165 176]
  ...
  [ 81  58  44]
  [ 79  58  44]
  [ 79  58  44]]

 [[164 179 190]
  [162 177 188]
  [159 174 185]
  ...
  [ 81  58  44]
  [ 79  58  44]
  [ 79  58  44]]

 ...

 [[ 91  89  94]
  [ 91  89  94]
  [ 91  89  94]
  ...
  [ 47  42  41]
  [ 47  42  41]
  [ 47  42  41]]

 [[ 91  89  94]
  [ 91  89  94]
  [ 91  89  94]
  ...
  [ 47  42  41]
  [ 47  42  41]
  [ 47  42  41]]

 [[ 91  89  94]
  [ 91  89  94]
  [ 91  89  94]
  ...
  [ 47  42  41]
  [ 47  42  41]
  [ 47  42  41]]]
[[[150 165 176]
  [148 163 174]
  [146 158 170]
  ...
  [ 82  59  45]
  [ 79  58  44]
  [ 79  58  44]]

 [[159 174 185]
  [157 172 183]
  [157 169 181]
  ...
  [ 81  58  44]
  [ 79  58  44]
  [ 79  58  44]]

 [[166 181 192]
  [165 180 191]
  [168 180 192]
  ...
  [ 81  58  44]
  [ 79  58  44]
  [ 77  56  42]]

 ...

 [[ 81  79  84]
  [ 81  79  84]
  [ 81  79  84]
  ..

[[[178 190 202]
  [178 190 202]
  [177 189 201]
  ...
  [218 189 165]
  [222 190 162]
  [222 190 162]]

 [[163 175 187]
  [163 175 187]
  [161 173 185]
  ...
  [218 189 165]
  [222 190 162]
  [222 190 162]]

 [[178 190 202]
  [178 190 202]
  [175 187 199]
  ...
  [218 189 165]
  [222 189 163]
  [222 189 163]]

 ...

 [[ 88  83  89]
  [ 88  83  89]
  [ 90  85  91]
  ...
  [ 47  42  41]
  [ 47  42  41]
  [ 47  42  41]]

 [[ 87  83  86]
  [ 87  83  86]
  [ 89  85  88]
  ...
  [ 47  42  41]
  [ 47  42  41]
  [ 47  42  41]]

 [[ 88  84  87]
  [ 88  84  87]
  [ 89  85  88]
  ...
  [ 47  42  41]
  [ 47  42  41]
  [ 47  42  41]]]
[[[186 198 210]
  [186 198 210]
  [185 197 209]
  ...
  [220 190 163]
  [222 190 162]
  [222 190 162]]

 [[167 179 191]
  [167 179 191]
  [166 178 190]
  ...
  [220 190 163]
  [222 190 162]
  [222 190 162]]

 [[167 179 191]
  [167 179 191]
  [166 178 190]
  ...
  [221 187 164]
  [221 188 162]
  [221 188 162]]

 ...

 [[ 89  85  88]
  [ 89  85  88]
  [ 89  85  88]
  ..

[[[188 207 218]
  [188 207 218]
  [188 207 218]
  ...
  [222 190 168]
  [220 187 168]
  [219 186 167]]

 [[187 206 217]
  [187 206 217]
  [187 206 217]
  ...
  [222 190 168]
  [220 187 168]
  [217 184 165]]

 [[187 206 215]
  [187 206 215]
  [187 206 215]
  ...
  [221 189 167]
  [219 186 167]
  [217 184 165]]

 ...

 [[103  99 102]
  [103  99 102]
  [103  99 102]
  ...
  [ 49  47  43]
  [ 49  47  43]
  [ 49  47  43]]

 [[102  98 101]
  [102  98 101]
  [102  98 101]
  ...
  [ 49  47  43]
  [ 49  47  43]
  [ 49  47  43]]

 [[102  98 101]
  [102  98 101]
  [102  98 101]
  ...
  [ 49  47  43]
  [ 49  47  43]
  [ 49  47  43]]]
[[[195 213 220]
  [195 213 220]
  [195 213 220]
  ...
  [217 185 163]
  [216 184 162]
  [215 183 161]]

 [[195 213 220]
  [195 213 220]
  [195 213 220]
  ...
  [215 183 161]
  [214 182 160]
  [213 181 159]]

 [[195 213 220]
  [195 213 220]
  [195 213 220]
  ...
  [215 184 160]
  [213 182 158]
  [213 182 158]]

 ...

 [[103  99 102]
  [103  99 102]
  [105 101 104]
  ..

[[[194 213 217]
  [190 209 213]
  [181 199 206]
  ...
  [109  77  69]
  [113  81  75]
  [118  86  80]]

 [[195 214 218]
  [189 208 212]
  [181 199 206]
  ...
  [106  74  66]
  [110  78  72]
  [115  83  77]]

 [[194 213 217]
  [187 206 210]
  [180 196 203]
  ...
  [100  72  66]
  [ 98  72  67]
  [ 99  73  68]]

 ...

 [[113 109 112]
  [113 109 112]
  [112 108 111]
  ...
  [ 52  50  46]
  [ 52  50  46]
  [ 52  50  46]]

 [[113 109 112]
  [113 109 112]
  [111 107 110]
  ...
  [ 52  50  46]
  [ 52  50  46]
  [ 52  50  46]]

 [[113 109 112]
  [113 109 112]
  [111 107 110]
  ...
  [ 52  50  46]
  [ 52  50  46]
  [ 52  50  46]]]
[[[165 177 182]
  [165 177 182]
  [165 177 182]
  ...
  [104  74  68]
  [108  77  73]
  [113  82  78]]

 [[163 175 180]
  [163 175 180]
  [163 175 180]
  ...
  [102  72  66]
  [102  71  67]
  [103  72  68]]

 [[163 175 180]
  [163 175 180]
  [163 175 180]
  ...
  [ 92  66  61]
  [ 92  66  61]
  [ 93  67  62]]

 ...

 [[ 96  98 105]
  [ 99 101 108]
  [ 94  99 110]
  ..

[[[205 220 231]
  [205 220 231]
  [206 221 232]
  ...
  [ 91  74  68]
  [ 86  73  69]
  [ 85  72  68]]

 [[205 220 231]
  [205 220 231]
  [206 221 232]
  ...
  [ 91  74  68]
  [ 86  73  69]
  [ 85  72  68]]

 [[205 220 231]
  [205 220 231]
  [206 221 232]
  ...
  [ 91  74  68]
  [ 86  73  69]
  [ 85  72  68]]

 ...

 [[109 105 108]
  [109 105 108]
  [107 103 106]
  ...
  [ 52  48  44]
  [ 52  48  44]
  [ 52  48  44]]

 [[109 105 108]
  [109 105 108]
  [107 103 106]
  ...
  [ 52  48  44]
  [ 52  48  44]
  [ 52  48  44]]

 [[109 105 108]
  [109 105 108]
  [107 103 106]
  ...
  [ 52  48  44]
  [ 52  48  44]
  [ 52  48  44]]]
[[[197 212 223]
  [198 213 224]
  [198 213 224]
  ...
  [ 94  75  69]
  [ 86  73  69]
  [ 86  73  69]]

 [[197 212 223]
  [198 213 224]
  [198 213 224]
  ...
  [ 94  75  69]
  [ 86  73  69]
  [ 86  73  69]]

 [[198 213 224]
  [199 214 225]
  [200 215 226]
  ...
  [ 94  75  69]
  [ 86  73  69]
  [ 86  73  69]]

 ...

 [[112 105 111]
  [112 105 111]
  [111 104 110]
  ..

[[[212 224 236]
  [202 214 226]
  [172 184 196]
  ...
  [231 203 176]
  [228 200 173]
  [227 199 172]]

 [[199 211 223]
  [200 212 224]
  [180 192 204]
  ...
  [228 200 173]
  [226 198 171]
  [227 199 172]]

 [[189 199 211]
  [203 213 225]
  [195 205 217]
  ...
  [228 198 171]
  [227 197 170]
  [227 197 170]]

 ...

 [[114 107 113]
  [114 107 113]
  [114 107 113]
  ...
  [ 52  48  44]
  [ 52  48  44]
  [ 52  48  44]]

 [[112 105 111]
  [112 105 111]
  [112 105 111]
  ...
  [ 52  48  44]
  [ 52  48  44]
  [ 52  48  44]]

 [[112 105 111]
  [112 105 111]
  [112 105 111]
  ...
  [ 52  48  44]
  [ 52  48  44]
  [ 52  48  44]]]
[[[192 206 211]
  [192 206 211]
  [192 206 211]
  ...
  [234 209 181]
  [230 205 177]
  [227 202 174]]

 [[208 222 227]
  [209 223 228]
  [209 223 228]
  ...
  [234 209 181]
  [230 205 177]
  [227 202 174]]

 [[216 230 235]
  [217 231 236]
  [217 231 236]
  ...
  [234 206 179]
  [229 201 174]
  [228 200 173]]

 ...

 [[108 101 107]
  [108 101 107]
  [109 102 108]
  ..

[[[185 193 192]
  [187 195 194]
  [188 196 195]
  ...
  [ 38  34  30]
  [ 38  34  30]
  [ 38  34  30]]

 [[185 193 192]
  [187 195 194]
  [188 196 195]
  ...
  [ 38  34  30]
  [ 38  34  30]
  [ 38  34  30]]

 [[185 193 192]
  [187 195 194]
  [188 196 195]
  ...
  [ 38  34  30]
  [ 38  34  30]
  [ 38  34  30]]

 ...

 [[ 35  50  53]
  [ 32  47  50]
  [ 38  46  50]
  ...
  [  5   4   6]
  [  5   4   6]
  [  5   4   6]]

 [[ 52  96  94]
  [ 46  90  88]
  [ 41  66  67]
  ...
  [  5   4   6]
  [  5   4   6]
  [  5   4   6]]

 [[ 79 123 121]
  [ 61 105 103]
  [ 34  59  60]
  ...
  [  5   4   6]
  [  5   4   6]
  [  5   4   6]]]
[[[185 193 192]
  [187 195 194]
  [188 196 195]
  ...
  [ 38  34  30]
  [ 38  34  30]
  [ 38  34  30]]

 [[185 193 192]
  [187 195 194]
  [188 196 195]
  ...
  [ 38  34  30]
  [ 38  34  30]
  [ 38  34  30]]

 [[185 193 192]
  [187 195 194]
  [188 196 195]
  ...
  [ 38  34  30]
  [ 38  34  30]
  [ 38  34  30]]

 ...

 [[ 26  39  42]
  [ 25  38  41]
  [ 36  39  44]
  ..

[[[112 109 116]
  [118 115 122]
  [130 127 134]
  ...
  [ 43  36  33]
  [ 43  36  33]
  [ 43  36  33]]

 [[137 134 141]
  [146 143 150]
  [153 150 157]
  ...
  [ 43  36  33]
  [ 43  36  33]
  [ 43  36  33]]

 [[156 153 160]
  [164 161 168]
  [165 162 169]
  ...
  [ 43  36  33]
  [ 42  35  32]
  [ 42  35  32]]

 ...

 [[ 46  51  64]
  [ 38  43  56]
  [ 40  50  62]
  ...
  [  5   4   6]
  [  5   4   6]
  [  5   4   6]]

 [[ 79  84  97]
  [ 63  68  81]
  [ 44  51  64]
  ...
  [  5   4   6]
  [  5   4   6]
  [  5   4   6]]

 [[ 81  86  99]
  [ 80  85  98]
  [ 72  79  92]
  ...
  [  5   4   6]
  [  5   4   6]
  [  5   4   6]]]
[[[104 101 108]
  [104 101 108]
  [104 101 108]
  ...
  [ 43  36  33]
  [ 42  35  32]
  [ 42  35  32]]

 [[144 141 148]
  [144 141 148]
  [140 137 144]
  ...
  [ 43  36  33]
  [ 42  35  32]
  [ 42  35  32]]

 [[163 160 167]
  [163 160 167]
  [159 156 163]
  ...
  [ 43  36  33]
  [ 42  35  32]
  [ 42  35  32]]

 ...

 [[ 88  91 104]
  [ 88  91 104]
  [ 86  89 102]
  ..

[[[168 168 168]
  [168 168 168]
  [168 168 168]
  ...
  [ 51  44  41]
  [ 49  42  39]
  [ 46  39  36]]

 [[168 168 168]
  [168 168 168]
  [168 168 168]
  ...
  [ 51  44  41]
  [ 49  42  39]
  [ 46  39  36]]

 [[168 168 168]
  [168 168 168]
  [168 168 168]
  ...
  [ 51  44  41]
  [ 49  42  39]
  [ 46  39  36]]

 ...

 [[ 85  87  89]
  [ 85  87  89]
  [ 85  87  89]
  ...
  [ 15  15  13]
  [ 15  15  13]
  [ 15  15  13]]

 [[ 85  87  89]
  [ 85  87  89]
  [ 85  87  89]
  ...
  [ 16  16  14]
  [ 16  16  14]
  [ 16  16  14]]

 [[ 85  87  89]
  [ 85  87  89]
  [ 85  87  89]
  ...
  [ 22  22  20]
  [ 22  22  20]
  [ 22  22  20]]]
[[[151 151 151]
  [149 149 149]
  [142 142 142]
  ...
  [ 41  37  33]
  [ 41  37  33]
  [ 41  37  33]]

 [[129 129 129]
  [122 122 122]
  [117 117 117]
  ...
  [ 40  36  32]
  [ 40  36  32]
  [ 40  36  32]]

 [[ 85  85  85]
  [ 83  83  83]
  [ 88  88  88]
  ...
  [ 40  36  32]
  [ 40  36  32]
  [ 40  36  32]]

 ...

 [[ 85  84  86]
  [ 85  84  86]
  [ 86  85  87]
  ..

[[[252 253 248]
  [252 253 248]
  [252 253 248]
  ...
  [111  96  83]
  [ 76  61  48]
  [ 74  59  46]]

 [[252 253 248]
  [252 253 248]
  [252 253 248]
  ...
  [111  96  83]
  [ 76  61  48]
  [ 74  59  46]]

 [[252 253 248]
  [252 253 248]
  [252 253 248]
  ...
  [110  95  82]
  [ 82  67  54]
  [ 80  65  52]]

 ...

 [[175 177 179]
  [164 166 168]
  [142 144 146]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]

 [[185 187 189]
  [183 185 187]
  [177 179 181]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]

 [[169 171 173]
  [171 173 175]
  [175 177 179]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]]
[[[252 253 248]
  [252 253 248]
  [252 253 248]
  ...
  [ 77  61  51]
  [ 67  51  41]
  [ 64  48  38]]

 [[252 253 248]
  [252 253 248]
  [252 253 248]
  ...
  [ 77  61  51]
  [ 67  51  41]
  [ 64  48  38]]

 [[252 253 248]
  [252 253 248]
  [252 253 248]
  ...
  [ 78  62  52]
  [ 67  51  41]
  [ 64  48  38]]

 ...

 [[167 174 175]
  [171 178 179]
  [172 179 180]
  ..

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 49  32  26]
  [ 49  32  26]
  [ 49  32  26]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 50  33  27]
  [ 49  32  26]
  [ 49  32  26]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 50  33  27]
  [ 50  33  27]
  [ 50  33  27]]

 ...

 [[ 26  22  25]
  [ 34  30  33]
  [ 98  94  97]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]

 [[ 12   8  11]
  [ 28  24  27]
  [ 68  64  67]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]

 [[ 18  14  17]
  [ 24  20  23]
  [ 28  24  27]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 49  32  26]
  [ 49  32  26]
  [ 50  33  27]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 50  33  27]
  [ 49  32  26]
  [ 50  33  27]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 50  33  27]
  [ 50  33  27]
  [ 50  33  27]]

 ...

 [[ 14  10  13]
  [ 21  17  20]
  [ 66  62  65]
  ..

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 54  34  26]
  [ 50  31  25]
  [ 51  32  26]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 54  34  26]
  [ 50  31  25]
  [ 51  32  26]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 56  36  28]
  [ 51  32  26]
  [ 51  32  26]]

 ...

 [[161 169 168]
  [161 169 168]
  [161 169 168]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]

 [[161 169 168]
  [161 169 168]
  [161 169 168]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]

 [[161 169 168]
  [161 169 168]
  [161 169 168]
  ...
  [  8   4   7]
  [  8   4   7]
  [  8   4   7]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 54  34  26]
  [ 50  31  25]
  [ 50  31  25]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 54  34  26]
  [ 50  31  25]
  [ 50  31  25]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 56  36  28]
  [ 51  32  26]
  [ 50  31  25]]

 ...

 [[161 169 168]
  [161 169 168]
  [161 169 168]
  ..

[[[254 252 243]
  [254 252 243]
  [253 252 241]
  ...
  [119 101  91]
  [116  98  88]
  [114  96  86]]

 [[254 252 243]
  [255 255 250]
  [255 255 253]
  ...
  [119 101  91]
  [115  97  87]
  [114  96  86]]

 [[255 255 249]
  [255 255 255]
  [255 255 255]
  ...
  [119 101  91]
  [116  98  88]
  [114  96  86]]

 ...

 [[ 75  78  76]
  [ 73  76  74]
  [ 73  76  74]
  ...
  [  7   3   6]
  [  7   3   6]
  [  7   3   6]]

 [[ 75  78  76]
  [ 73  76  74]
  [ 73  76  74]
  ...
  [  7   3   6]
  [  7   3   6]
  [  7   3   6]]

 [[ 75  78  76]
  [ 73  76  74]
  [ 73  76  74]
  ...
  [  7   3   6]
  [  7   3   6]
  [  7   3   6]]]
[[[255 253 244]
  [254 252 243]
  [255 255 244]
  ...
  [118 100  90]
  [114  96  86]
  [113  95  85]]

 [[255 253 244]
  [255 255 246]
  [255 255 255]
  ...
  [119 101  91]
  [116  98  88]
  [114  96  86]]

 [[255 255 255]
  [255 255 253]
  [255 255 248]
  ...
  [119 101  91]
  [115  97  87]
  [114  96  86]]

 ...

 [[ 75  78  76]
  [ 73  76  74]
  [ 73  76  74]
  ..

[[[128 128 128]
  [101 101 101]
  [ 98  98  98]
  ...
  [112  97  84]
  [112  97  84]
  [112  97  84]]

 [[131 131 131]
  [119 119 119]
  [125 125 125]
  ...
  [111  96  83]
  [111  96  83]
  [111  96  83]]

 [[144 144 144]
  [143 143 143]
  [144 144 144]
  ...
  [111  96  83]
  [111  96  83]
  [111  96  83]]

 ...

 [[ 73  73  73]
  [ 73  73  73]
  [ 73  73  73]
  ...
  [  7   3   6]
  [  7   3   6]
  [  7   3   6]]

 [[ 73  73  73]
  [ 73  73  73]
  [ 73  73  73]
  ...
  [  7   3   6]
  [  7   3   6]
  [  7   3   6]]

 [[ 73  73  73]
  [ 73  73  73]
  [ 73  73  73]
  ...
  [  7   3   6]
  [  7   3   6]
  [  7   3   6]]]
[[[164 163 165]
  [187 186 188]
  [204 203 205]
  ...
  [112  97  84]
  [112  97  84]
  [112  97  84]]

 [[159 158 160]
  [189 188 190]
  [206 205 207]
  ...
  [111  96  83]
  [111  96  83]
  [111  96  83]]

 [[170 169 171]
  [189 188 190]
  [203 202 204]
  ...
  [111  96  83]
  [111  96  83]
  [111  96  83]]

 ...

 [[ 73  73  73]
  [ 73  73  73]
  [ 73  73  73]
  ..

[[[118 111 117]
  [132 125 131]
  [139 132 138]
  ...
  [ 51  44  41]
  [ 54  48  43]
  [ 70  64  59]]

 [[160 153 159]
  [151 144 150]
  [139 132 138]
  ...
  [ 50  43  40]
  [ 52  46  41]
  [ 67  61  56]]

 [[127 122 128]
  [104  99 105]
  [ 95  89  97]
  ...
  [ 51  45  40]
  [ 53  48  40]
  [ 68  63  55]]

 ...

 [[ 82  79  80]
  [ 82  79  80]
  [ 82  79  80]
  ...
  [ 17  13  16]
  [ 17  13  16]
  [ 17  13  16]]

 [[ 82  79  80]
  [ 82  79  80]
  [ 82  79  80]
  ...
  [ 17  13  16]
  [ 17  13  16]
  [ 17  13  16]]

 [[ 82  79  80]
  [ 82  79  80]
  [ 82  79  80]
  ...
  [ 17  13  16]
  [ 17  13  16]
  [ 17  13  16]]]
[[[148 141 147]
  [140 133 139]
  [128 120 128]
  ...
  [ 46  40  35]
  [ 51  43  38]
  [ 59  51  46]]

 [[119 112 118]
  [111 104 110]
  [100  92 100]
  ...
  [ 47  41  36]
  [ 51  43  38]
  [ 59  51  46]]

 [[ 80  74  82]
  [ 82  76  84]
  [ 81  75  83]
  ...
  [ 50  44  39]
  [ 53  45  40]
  [ 61  53  48]]

 ...

 [[ 80  77  78]
  [ 80  77  78]
  [ 80  77  78]
  ..

[[[166 166 166]
  [168 168 168]
  [163 163 163]
  ...
  [ 46  41  33]
  [ 45  40  32]
  [ 46  41  33]]

 [[176 176 176]
  [178 178 178]
  [178 178 178]
  ...
  [ 45  40  32]
  [ 45  40  32]
  [ 46  41  33]]

 [[187 187 187]
  [171 171 171]
  [140 140 140]
  ...
  [ 45  40  32]
  [ 46  41  33]
  [ 46  41  33]]

 ...

 [[ 73  73  73]
  [ 73  73  73]
  [ 73  73  73]
  ...
  [ 15  10   9]
  [ 15  10   9]
  [ 15  10   9]]

 [[ 72  72  72]
  [ 72  72  72]
  [ 72  72  72]
  ...
  [ 15  10   9]
  [ 15  10   9]
  [ 15  10   9]]

 [[ 72  72  72]
  [ 72  72  72]
  [ 72  72  72]
  ...
  [ 15  10   9]
  [ 15  10   9]
  [ 15  10   9]]]
[[[174 174 174]
  [173 173 173]
  [180 180 180]
  ...
  [ 45  40  32]
  [ 45  40  32]
  [ 45  40  32]]

 [[175 175 175]
  [167 167 167]
  [150 150 150]
  ...
  [ 45  40  32]
  [ 46  41  33]
  [ 46  41  33]]

 [[167 167 167]
  [108 108 108]
  [ 76  76  76]
  ...
  [ 44  39  31]
  [ 45  40  32]
  [ 46  41  33]]

 ...

 [[ 73  73  73]
  [ 73  73  73]
  [ 73  73  73]
  ..

# Detecting Both Pedestrian And The Cars in the video

In [ ]:
import cv2,time
pedestrian_detector = cv2.CascadeClassifier('pedestrian.xml')
car_cascade = cv2.CascadeClassifier('cars.xml')
video = cv2.VideoCapture('Pedestrians Compilation 480 x 854.mp4')

a = 1
while True:
    a = a+1
    check,frame = video.read()
    print(frame)
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    pedestrians = pedestrian_detector.detectMultiScale(gray , 3.5 , 1)
    
    for (x,y,w,h) in pedestrians:
        cv2.rectangle(frame,(x,y) , (x+w , y+h) , (255,0,0) , 2)
    
    resize = cv2.resize(frame, (640, 480)) 
    cv2.imshow("car", resize) 
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows()